[WIP] Log in to VMI serial console
kiagnose/kubevirt-dpdk-checkup pull request #34
Opened 2023-01-31 19:42 UTC by orelmisan

Try to log in to the VMI serial console, in order to perform the necessary commands required to perform the checkup.

The `console` code is based on code from KubeVirt e2e tests suite [1]

[1] https://github.com/kubevirt/kubevirt/tree/ef62d0f87a95580c2c449fa4bbd1c5a13d15d81a/tests/console

2023-02-01 22:29 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kubevirt-dpdk-checkup/compare/4849008e52125830bf41ed8a078b426b2ebb102c..d9de8a3cb08cc75eb4879f6cae8da2347abd902a): Taken the namespace out of the `Execute()` function, so it could be shared between the VMI and the Pod.

2023-02-02 06:57 UTC, RamLavi requested changes

2023-02-02 08:25 UTC, orelmisan commented on pkg/internal/checkup/console/login.go
> +func LoginToCentOS(serialConsoleClient vmiSerialConsoleClient, vmi *kvcorev1.VirtualMachineInstance, username, password string) error {
Yes.

2023-02-02 08:29 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kubevirt-dpdk-checkup/compare/d9de8a3cb08cc75eb4879f6cae8da2347abd902a..05144b2afc31bdc0efbd07063f9d20c1eb102c9f): Rebase

2023-02-02 08:32 UTC, orelmisan commented on pkg/internal/checkup/executor/executor.go
> +type vmiSerialConsoleClient interface {
I suggest to make the suggested change in the PR that will introduce the pod to the executor.
Right now, this is the minimal required functionality.

2023-02-02 08:39 UTC, RamLavi approved these changes
/lgtm

2023-02-02 08:43 UTC, merged